// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1ahirjQXNGa4KiYXB5BSTopjarHeiJH8',
    appId: '1:485911497764:web:63ef69b1799764edb71cb1',
    messagingSenderId: '485911497764',
    projectId: 'aiquizitive',
    authDomain: 'aiquizitive.firebaseapp.com',
    storageBucket: 'aiquizitive.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5tRb2ZfO73ZZApYYGhJBYvuc6O9fHuE8',
    appId: '1:485911497764:android:05aa2f43972eb740b71cb1',
    messagingSenderId: '485911497764',
    projectId: 'aiquizitive',
    storageBucket: 'aiquizitive.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Cg-nq96CBdX5mvFF5NCg5CuCES2v_zE',
    appId: '1:485911497764:ios:49e946fe2cb4a7e7b71cb1',
    messagingSenderId: '485911497764',
    projectId: 'aiquizitive',
    storageBucket: 'aiquizitive.appspot.com',
    iosBundleId: 'com.example.aiQuizitive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Cg-nq96CBdX5mvFF5NCg5CuCES2v_zE',
    appId: '1:485911497764:ios:49e946fe2cb4a7e7b71cb1',
    messagingSenderId: '485911497764',
    projectId: 'aiquizitive',
    storageBucket: 'aiquizitive.appspot.com',
    iosBundleId: 'com.example.aiQuizitive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1ahirjQXNGa4KiYXB5BSTopjarHeiJH8',
    appId: '1:485911497764:web:4a7037a7c44041adb71cb1',
    messagingSenderId: '485911497764',
    projectId: 'aiquizitive',
    authDomain: 'aiquizitive.firebaseapp.com',
    storageBucket: 'aiquizitive.appspot.com',
  );
}
